checkpoint 3 - attempt 1
zacharyehren/bloc-chat pull request #2
Opened 2017-01-07 23:27 UTC by zacharyehren

2017-01-07 23:31 UTC, zacharyehren commented on app/pages/index.html
> +  <script src="/node_modules/angular-ui-bootstrap/src/modal/modal.js"></script>
I used a local path for this. Should it actually be a remote path? Also, should it be higher in the list of script tags? I know the order of the script tags depends on which tag is dependent on the others.

2017-01-07 23:55 UTC, bmneely commented on app/pages/index.html
> +  <script src="/node_modules/angular-ui-bootstrap/src/modal/modal.js"></script>
This should work fine. `npm` will install the modules into the `node_modules` directory just like you have them included.

2017-01-08 00:01 UTC, bmneely requested changes

2017-01-08 00:01 UTC, bmneely commented on app/scripts/services/Room.js
> +    var newRoom = null;
You actually won't want to set this to `null` `newRoom` will only exist as function argument, not as a local variable in `Room`

2017-01-08 00:01 UTC, bmneely commented on app/scripts/services/Room.js
> +    }
This is exactly, right. To make this a public function for your service, you'll want to add this on line 15 as part of your return:

```javascript
      all: rooms,
      create: function(newRoom) {
        rooms.$add(newRoom); 
      }
```

2017-01-08 00:01 UTC, bmneely commented on dist/scripts/app.js
> +    //Do I need to inject the modal as a state?
You do not, because the modal isn't a new route in your app (it'll be open within an existing page, not when a new page is navigated to.

2017-01-14 01:42 UTC, merged